import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Download, FileSpreadsheet } from "lucide-react";
import { AppShell, EmptyState, useSchoolId } from "@/components/app-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/lib/auth";
import { api } from "@/lib/queries";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/exports")({component:ExportsPage});
function download(name:string,rows:string[][]){const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();}
function ExportsPage(){const schoolId=useSchoolId();const {primaryRole}=useAuth();const allowed=["school_admin","principal","secretary"].includes(primaryRole??"");const students=useQuery({queryKey:["export-students",schoolId],enabled:!!schoolId&&allowed,queryFn:()=>api.students(schoolId!)});const teachers=useQuery({queryKey:["export-teachers",schoolId],enabled:!!schoolId&&allowed,queryFn:()=>api.teachers(schoolId!)});const finance=useQuery({queryKey:["export-finance",schoolId],enabled:!!schoolId&&allowed,queryFn:async()=>{const [a,p]=await Promise.all([supabase.from("fee_assignments").select("id,student_id,fee_type_id,amount_due,status,due_date").eq("school_id",schoolId!),supabase.from("fee_payments").select("id,student_id,fee_assignment_id,amount,payment_date,method,reference,receipt_number").eq("school_id",schoolId!).order("payment_date",{ascending:false})]);if(a.error)throw new Error(a.error.message);if(p.error)throw new Error(p.error.message);return {assignments:a.data??[],payments:p.data??[]};}});const attendance=useQuery({queryKey:["export-attendance",schoolId],enabled:!!schoolId&&allowed,queryFn:async()=>{const [s,r]=await Promise.all([supabase.from("attendance_sessions").select("id,class_id,session_date,period").eq("school_id",schoolId!).order("session_date",{ascending:false}),supabase.from("attendance_records").select("attendance_session_id,student_id,status").eq("school_id",schoolId!)]);if(s.error)throw new Error(s.error.message);if(r.error)throw new Error(r.error.message);return {sessions:s.data??[],records:r.data??[]};}});const teacherAttendance=useQuery({queryKey:["export-teacher-attendance",schoolId],enabled:!!schoolId&&allowed,queryFn:async()=>{const {data,error}=await supabase.from("teacher_attendance").select("teacher_id,attendance_date,clock_in,clock_out,note").eq("school_id",schoolId!).order("attendance_date",{ascending:false});if(error)throw new Error(error.message);return data??[];}});
 if(!allowed)return <AppShell title="Exports"><EmptyState icon={FileSpreadsheet} title="Export access required" description="Only school managers and the Secretary can export administrative data."/></AppShell>;
 const studentRows=[["Student ID","First name","Last name","Email","Phone","Class","Admission date","Archived"],...(students.data??[]).map(s=>[s.student_id,s.first_name,s.last_name,s.email??"",s.phone??"",s.class_id??"",s.admission_date??"",String(s.is_archived)])];const teacherRows=[["Staff ID","First name","Last name","Email","Phone","Active"],...(teachers.data??[]).map(t=>[t.staff_id,t.first_name,t.last_name,t.email??"",t.phone??"",String(t.is_active)])];const feeRows=[["Student ID","Student","Fee","Due","Paid","Balance","Status"],...(finance.data?.assignments??[]).map(a=>{const s=(students.data??[]).find(x=>x.id===a.student_id);const paid=(finance.data?.payments??[]).filter(p=>p.fee_assignment_id===a.id).reduce((n,p)=>n+Number(p.amount),0);return [s?.student_id??"",s?`${s.first_name} ${s.last_name}`:"Unknown",a.fee_type_id,Number(a.amount_due).toFixed(2),paid.toFixed(2),Math.max(Number(a.amount_due)-paid,0).toFixed(2),a.status];})];const paymentRows=[["Receipt","Student ID","Amount","Date","Method","Reference"],...(finance.data?.payments??[]).map(p=>{const s=(students.data??[]).find(x=>x.id===p.student_id);return [p.receipt_number,s?.student_id??"",Number(p.amount).toFixed(2),new Date(p.payment_date).toISOString(),p.method,p.reference??""];})];const attRows=[["Date","Period","Class ID","Student ID","Status"],...(attendance.data?.records??[]).map(r=>{const s=(attendance.data?.sessions??[]).find(x=>x.id===r.attendance_session_id);return [s?.session_date??"",s?.period??"",s?.class_id??"",r.student_id,r.status];})];const teacherAttRows=[["Date","Teacher ID","Clock in","Clock out","Note"],...(teacherAttendance.data??[]).map(r=>[r.attendance_date,r.teacher_id,r.clock_in?new Date(r.clock_in).toISOString():"",r.clock_out?new Date(r.clock_out).toISOString():"",r.note??""])];const cards=[{title:"Students",desc:"Student records and current class assignments",name:"students.csv",rows:studentRows},{title:"Fee status",desc:"Expected, paid, balance and payment status",name:"fee-status.csv",rows:feeRows},{title:"Payment history",desc:"Recorded payments and receipt references",name:"payment-history.csv",rows:paymentRows},{title:"Student attendance",desc:"Attendance sessions and student statuses",name:"student-attendance.csv",rows:attRows},{title:"Teacher attendance",desc:"Staff clock-in and clock-out history",name:"teacher-attendance.csv",rows:teacherAttRows}];return <AppShell title="Administrative Exports" description="Download authorized school records as CSV"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cards.map(c=><Card key={c.title}><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileSpreadsheet className="size-4"/>{c.title}</CardTitle></CardHeader><CardContent><p className="min-h-10 text-sm text-muted-foreground">{c.desc}</p><Button className="mt-4 w-full" variant="outline" onClick={()=>download(c.name,c.rows)}><Download className="size-4"/>Export CSV</Button></CardContent></Card>)}</div></AppShell>;
}