import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Banknote, Download, Loader2, Plus, Receipt, Search } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState, useSchoolId } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { api } from "@/lib/queries";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/_authenticated/finance")({ component: FinancePage });
type FeeType = { id:string; name:string; description:string|null; amount:number; frequency:string; is_active:boolean };
type FeeAssignment = { id:string; fee_type_id:string; student_id:string; amount_due:number; due_date:string|null; status:string; session_id:string|null; term_id:string|null };
type Payment = { id:string; fee_assignment_id:string; student_id:string; amount:number; payment_date:string; method:string; reference:string|null; receipt_number:string; note:string|null };
function csv(name:string, rows:string[][]) { const text=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"); const url=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"})); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }
function FinancePage(){
 const schoolId=useSchoolId(); const {primaryRole}=useAuth(); const qc=useQueryClient(); const canManage=primaryRole==="secretary"||primaryRole==="school_admin"||primaryRole==="principal";
 const students=useQuery({queryKey:["students",schoolId],enabled:!!schoolId,queryFn:()=>api.students(schoolId!)});
 const feeTypes=useQuery({queryKey:["fee-types",schoolId],enabled:!!schoolId,queryFn:async()=>{const {data,error}=await supabase.from("fee_types").select("id,name,description,amount,frequency,is_active").order("name");if(error)throw new Error(error.message);return (data??[]) as FeeType[];}});
 const assignments=useQuery({queryKey:["fee-assignments",schoolId],enabled:!!schoolId,queryFn:async()=>{const {data,error}=await supabase.from("fee_assignments").select("id,fee_type_id,student_id,amount_due,due_date,status,session_id,term_id").order("created_at",{ascending:false});if(error)throw new Error(error.message);return (data??[]) as FeeAssignment[];}});
 const payments=useQuery({queryKey:["fee-payments",schoolId],enabled:!!schoolId,queryFn:async()=>{const {data,error}=await supabase.from("fee_payments").select("id,fee_assignment_id,student_id,amount,payment_date,method,reference,receipt_number,note").order("payment_date",{ascending:false});if(error)throw new Error(error.message);return (data??[]) as Payment[];}});
 const [fee,setFee]=useState({name:"",amount:"",frequency:"term",description:""}); const [assignment,setAssignment]=useState({fee_type_id:"",student_id:"",amount_due:"",due_date:""}); const [payment,setPayment]=useState({fee_assignment_id:"",amount:"",method:"cash",reference:"",note:""}); const [search,setSearch]=useState("");
 const createFee=useMutation({mutationFn:async()=>{if(!schoolId||!fee.name.trim()||!fee.amount)throw new Error("Fee name and amount are required");const {error}=await supabase.from("fee_types").insert({school_id:schoolId,name:fee.name.trim(),amount:Number(fee.amount),frequency:fee.frequency,description:fee.description.trim()||null});if(error)throw new Error(error.message);},onSuccess:async()=>{setFee({name:"",amount:"",frequency:"term",description:""});toast.success("Fee type created");await qc.invalidateQueries({queryKey:["fee-types",schoolId]});},onError:e=>toast.error(e.message)});
 const createAssignment=useMutation({mutationFn:async()=>{if(!schoolId||!assignment.fee_type_id||!assignment.student_id||!assignment.amount_due)throw new Error("Select a fee and student and enter an amount");const {error}=await supabase.from("fee_assignments").insert({school_id:schoolId,fee_type_id:assignment.fee_type_id,student_id:assignment.student_id,amount_due:Number(assignment.amount_due),due_date:assignment.due_date||null});if(error)throw new Error(error.message);},onSuccess:async()=>{setAssignment({fee_type_id:"",student_id:"",amount_due:"",due_date:""});toast.success("Fee assigned");await qc.invalidateQueries({queryKey:["fee-assignments",schoolId]});},onError:e=>toast.error(e.message)});
 const createPayment=useMutation({mutationFn:async()=>{if(!schoolId||!payment.fee_assignment_id||!payment.amount||Number(payment.amount)<=0)throw new Error("Select an outstanding fee and enter a valid payment");const a=(assignments.data??[]).find(x=>x.id===payment.fee_assignment_id);if(!a)throw new Error("Fee assignment not found");const paid=(payments.data??[]).filter(p=>p.fee_assignment_id===a.id).reduce((s,p)=>s+Number(p.amount),0);if(Number(payment.amount)>Number(a.amount_due)-paid+0.0001)throw new Error("Payment exceeds the outstanding balance");const {error}=await supabase.from("fee_payments").insert({school_id:schoolId,fee_assignment_id:a.id,student_id:a.student_id,amount:Number(payment.amount),method:payment.method,reference:payment.reference.trim()||null,note:payment.note.trim()||null});if(error)throw new Error(error.message);},onSuccess:async()=>{setPayment({fee_assignment_id:"",amount:"",method:"cash",reference:"",note:""});toast.success("Payment recorded");await qc.invalidateQueries({queryKey:["fee-payments",schoolId]});await qc.invalidateQueries({queryKey:["fee-assignments",schoolId]});},onError:e=>toast.error(e.message)});
 const rows=useMemo(()=>{const s=search.trim().toLowerCase();return (assignments.data??[]).map(a=>{const student=(students.data??[]).find(x=>x.id===a.student_id);const type=(feeTypes.data??[]).find(x=>x.id===a.fee_type_id);const paid=(payments.data??[]).filter(p=>p.fee_assignment_id===a.id).reduce((n,p)=>n+Number(p.amount),0);return {...a,studentName:student?`${student.first_name} ${student.last_name}`:"Unknown",studentCode:student?.student_id??"",feeName:type?.name??"Fee",paid,balance:Math.max(Number(a.amount_due)-paid,0)};}).filter(r=>!s||`${r.studentName} ${r.studentCode} ${r.feeName}`.toLowerCase().includes(s));},[assignments.data,students.data,feeTypes.data,payments.data,search]);
 const totals=rows.reduce((x,r)=>({due:x.due+Number(r.amount_due),paid:x.paid+r.paid,balance:x.balance+r.balance}),{due:0,paid:0,balance:0});
 const outstanding=rows.filter(r=>r.balance>0);
 if(!canManage)return <AppShell title="Finance" description="Fees and payments"><EmptyState icon={Banknote} title="Finance access required" description="Finance is available to school managers and the Secretary."/></AppShell>;
 return <AppShell title="Finance" description="Fees, payments, outstanding balances and receipts"><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Expected</p><p className="mt-1 text-2xl font-bold">₦{totals.due.toLocaleString()}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Collected</p><p className="mt-1 text-2xl font-bold">₦{totals.paid.toLocaleString()}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Outstanding</p><p className="mt-1 text-2xl font-bold">₦{totals.balance.toLocaleString()}</p></CardContent></Card></div>
 <Tabs defaultValue="outstanding"><TabsList><TabsTrigger value="outstanding">Outstanding</TabsTrigger><TabsTrigger value="fees">Fee types</TabsTrigger><TabsTrigger value="assign">Assign fees</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger></TabsList>
 <TabsContent value="outstanding" className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search student or fee" value={search} onChange={e=>setSearch(e.target.value)}/></div><Button variant="outline" onClick={()=>csv("eduflow-fee-status.csv",[["Student ID","Student","Fee","Due","Paid","Balance","Status"],...rows.map(r=>[r.studentCode,r.studentName,r.feeName,r.amount_due.toFixed(2),r.paid.toFixed(2),r.balance.toFixed(2),r.status])])}><Download className="size-4"/>Export CSV</Button></div>{outstanding.length===0?<EmptyState icon={Receipt} title="No outstanding balances" description="Students with unpaid or partially paid fees will appear here."/>:<div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Student</th><th className="p-3">Fee</th><th className="p-3">Due</th><th className="p-3">Paid</th><th className="p-3">Balance</th><th className="p-3">Status</th></tr></thead><tbody>{outstanding.map(r=><tr key={r.id} className="border-b"><td className="p-3"><p className="font-medium">{r.studentName}</p><p className="text-xs text-muted-foreground">{r.studentCode}</p></td><td className="p-3">{r.feeName}</td><td className="p-3">₦{Number(r.amount_due).toLocaleString()}</td><td className="p-3">₦{r.paid.toLocaleString()}</td><td className="p-3 font-semibold">₦{r.balance.toLocaleString()}</td><td className="p-3"><Badge variant={r.status==='partial'?"secondary":"destructive"}>{r.status}</Badge></td></tr>)}</tbody></table></div>}</TabsContent>
 <TabsContent value="fees"><Card><CardHeader><CardTitle>Create fee type</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div><Label>Name</Label><Input value={fee.name} onChange={e=>setFee({...fee,name:e.target.value})} placeholder="Tuition"/></div><div><Label>Amount</Label><Input type="number" min="0" value={fee.amount} onChange={e=>setFee({...fee,amount:e.target.value})} placeholder="150000"/></div><Select value={fee.frequency} onValueChange={v=>setFee({...fee,frequency:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="term">Per term</SelectItem><SelectItem value="session">Per session</SelectItem><SelectItem value="monthly">Monthly</SelectItem><SelectItem value="one_time">One time</SelectItem></SelectContent></Select><Textarea value={fee.description} onChange={e=>setFee({...fee,description:e.target.value})} placeholder="Description"/><Button onClick={()=>createFee.mutate()} disabled={createFee.isPending}><Plus className="size-4"/>Create fee type</Button></CardContent></Card><div className="mt-4 space-y-2">{(feeTypes.data??[]).map(f=><div key={f.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-medium">{f.name}</p><p className="text-xs text-muted-foreground">{f.frequency} · ₦{Number(f.amount).toLocaleString()}</p></div><Badge>{f.is_active?"Active":"Inactive"}</Badge></div>)}</div></TabsContent>
 <TabsContent value="assign"><Card><CardHeader><CardTitle>Assign a fee to a student</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Select value={assignment.fee_type_id} onValueChange={v=>{const f=(feeTypes.data??[]).find(x=>x.id===v);setAssignment({...assignment,fee_type_id:v,amount_due:f?String(f.amount):assignment.amount_due})}}><SelectTrigger><SelectValue placeholder="Fee type"/></SelectTrigger><SelectContent>{(feeTypes.data??[]).filter(f=>f.is_active).map(f=><SelectItem key={f.id} value={f.id}>{f.name} · ₦{Number(f.amount).toLocaleString()}</SelectItem>)}</SelectContent></Select><Select value={assignment.student_id} onValueChange={v=>setAssignment({...assignment,student_id:v})}><SelectTrigger><SelectValue placeholder="Student"/></SelectTrigger><SelectContent>{(students.data??[]).filter(s=>!s.is_archived).map(s=><SelectItem key={s.id} value={s.id}>{s.first_name} {s.last_name} · {s.student_id}</SelectItem>)}</SelectContent></Select><Input type="number" min="0" value={assignment.amount_due} onChange={e=>setAssignment({...assignment,amount_due:e.target.value})} placeholder="Amount due"/><Input type="date" value={assignment.due_date} onChange={e=>setAssignment({...assignment,due_date:e.target.value})}/><Button onClick={()=>createAssignment.mutate()} disabled={createAssignment.isPending}><Plus className="size-4"/>Assign fee</Button></CardContent></Card></TabsContent>
 <TabsContent value="payments"><Card><CardHeader><CardTitle>Record payment</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Select value={payment.fee_assignment_id} onValueChange={v=>{const a=rows.find(x=>x.id===v);setPayment({...payment,fee_assignment_id:v,amount:a?String(a.balance):payment.amount})}}><SelectTrigger><SelectValue placeholder="Outstanding fee"/></SelectTrigger><SelectContent>{outstanding.map(r=><SelectItem key={r.id} value={r.id}>{r.studentName} · {r.feeName} · ₦{r.balance.toLocaleString()} due</SelectItem>)}</SelectContent></Select><Input type="number" min="0" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} placeholder="Payment amount"/><Select value={payment.method} onValueChange={v=>setPayment({...payment,method:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="cash">Cash</SelectItem><SelectItem value="bank_transfer">Bank transfer</SelectItem><SelectItem value="card">Card</SelectItem><SelectItem value="pos">POS</SelectItem><SelectItem value="online">Online</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select><Input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})} placeholder="Reference (optional)"/><Textarea value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})} placeholder="Note"/><Button onClick={()=>createPayment.mutate()} disabled={createPayment.isPending}><Receipt className="size-4"/>Record payment</Button></CardContent></Card><div className="mt-4 space-y-2">{(payments.data??[]).slice(0,30).map(p=><div key={p.id} className="flex items-center justify-between rounded-xl border p-4"><div><p className="font-medium">{(students.data??[]).find(s=>s.id===p.student_id)?.first_name} {(students.data??[]).find(s=>s.id===p.student_id)?.last_name}</p><p className="text-xs text-muted-foreground">{p.receipt_number} · {new Date(p.payment_date).toLocaleString()} · {p.method}</p></div><p className="font-semibold">₦{Number(p.amount).toLocaleString()}</p></div>)}</div></TabsContent>
 </Tabs></div></AppShell>;
}