import * as React from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, ClipboardCheck, FileText, Megaphone, Plus, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState, useSchoolId } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { api } from "@/lib/queries";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/_authenticated/operations")({ component: OperationsPage });

function OperationsPage() {
  const schoolId = useSchoolId();
  const { user, isManager } = useAuth();
  const qc = useQueryClient();
  const classes = useQuery({ queryKey: ["classes", schoolId], enabled: !!schoolId, queryFn: () => api.classes(schoolId!) });
  const subjects = useQuery({ queryKey: ["subjects", schoolId], enabled: !!schoolId, queryFn: () => api.subjects(schoolId!) });
  const sessions = useQuery({ queryKey: ["sessions", schoolId], enabled: !!schoolId, queryFn: () => api.sessions(schoolId!) });
  const terms = useQuery({ queryKey: ["terms", schoolId], enabled: !!schoolId, queryFn: () => api.terms(schoolId!) });
  const assessments = useQuery({ queryKey: ["assessments", schoolId], enabled: !!schoolId, queryFn: () => api.assessments(schoolId!) });
  const assignments = useQuery({ queryKey: ["assignments", schoolId], enabled: !!schoolId, queryFn: () => api.assignments(schoolId!) });
  const announcements = useQuery({ queryKey: ["announcements", schoolId], enabled: !!schoolId, queryFn: () => api.announcements(schoolId!) });
  const [sessionName, setSessionName] = React.useState("");
  const [assessment, setAssessment] = React.useState({ title: "", class_id: "", subject_id: "", term_id: "", max_score: "100", type: "Test" });
  const [assignment, setAssignment] = React.useState({ title: "", class_id: "", subject_id: "", description: "", due_at: "" });
  const [announcement, setAnnouncement] = React.useState({ title: "", body: "", audience: "all" });

  const createSession = useMutation({ mutationFn: async () => { if (!schoolId || !sessionName.trim()) throw new Error("Session name is required"); const { error } = await supabase.from("academic_sessions").insert({ school_id: schoolId, name: sessionName.trim(), is_current: (sessions.data?.length ?? 0) === 0 }); if (error) throw new Error(error.message); }, onSuccess: async () => { setSessionName(""); toast.success("Academic session created"); await qc.invalidateQueries({ queryKey: ["sessions", schoolId] }); }, onError: e => toast.error(e.message) });
  const createAssessment = useMutation({ mutationFn: async () => { if (!schoolId || !assessment.title.trim() || !assessment.class_id || !assessment.subject_id || !assessment.term_id) throw new Error("Complete all assessment fields"); const sessionId = sessions.data?.find(s => s.is_current)?.id ?? sessions.data?.[0]?.id; if (!sessionId) throw new Error("Create an academic session first"); const { error } = await supabase.from("assessments").insert({ school_id: schoolId, session_id: sessionId, term_id: assessment.term_id, class_id: assessment.class_id, subject_id: assessment.subject_id, title: assessment.title.trim(), assessment_type: assessment.type, max_score: Number(assessment.max_score), weight: 100, published: false, created_by: user?.id }); if (error) throw new Error(error.message); }, onSuccess: async () => { setAssessment({ title: "", class_id: "", subject_id: "", term_id: "", max_score: "100", type: "Test" }); toast.success("Assessment created"); await qc.invalidateQueries({ queryKey: ["assessments", schoolId] }); }, onError: e => toast.error(e.message) });
  const createAssignment = useMutation({ mutationFn: async () => { if (!schoolId || !assignment.title.trim() || !assignment.class_id || !assignment.subject_id) throw new Error("Complete assignment title, class and subject"); const { error } = await supabase.from("assignments").insert({ school_id: schoolId, class_id: assignment.class_id, subject_id: assignment.subject_id, title: assignment.title.trim(), description: assignment.description.trim() || null, due_at: assignment.due_at || null, status: "published" }); if (error) throw new Error(error.message); }, onSuccess: async () => { setAssignment({ title: "", class_id: "", subject_id: "", description: "", due_at: "" }); toast.success("Assignment published"); await qc.invalidateQueries({ queryKey: ["assignments", schoolId] }); }, onError: e => toast.error(e.message) });
  const createAnnouncement = useMutation({ mutationFn: async () => { if (!schoolId || !announcement.title.trim() || !announcement.body.trim()) throw new Error("Title and message are required"); const { error } = await supabase.from("announcements").insert({ school_id: schoolId, title: announcement.title.trim(), body: announcement.body.trim(), audience: announcement.audience, published: true, published_at: new Date().toISOString(), created_by: user?.id }); if (error) throw new Error(error.message); }, onSuccess: async () => { setAnnouncement({ title: "", body: "", audience: "all" }); toast.success("Announcement published"); await qc.invalidateQueries({ queryKey: ["announcements", schoolId] }); }, onError: e => toast.error(e.message) });
  const remove = useMutation({ mutationFn: async ({ table, id }: { table: "assessments" | "assignments" | "announcements"; id: string }) => { const { error } = await supabase.from(table).delete().eq("id", id); if (error) throw new Error(error.message); }, onSuccess: async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["assessments", schoolId] }), qc.invalidateQueries({ queryKey: ["assignments", schoolId] }), qc.invalidateQueries({ queryKey: ["announcements", schoolId] })]); toast.success("Deleted"); }, onError: e => toast.error(e.message) });

  return <AppShell title="School Operations" description="Academic calendar, assessments, learning and communication">
    <Tabs defaultValue="calendar" className="space-y-5"><TabsList className="grid w-full grid-cols-4 lg:w-fit"><TabsTrigger value="calendar">Calendar</TabsTrigger><TabsTrigger value="assessments">Assessments</TabsTrigger><TabsTrigger value="learning">Learning</TabsTrigger><TabsTrigger value="communication">Communication</TabsTrigger></TabsList>
      <TabsContent value="calendar" className="space-y-5">{isManager && <Card><CardHeader><CardTitle>Academic sessions</CardTitle><CardDescription>Create school years and keep the academic timeline current.</CardDescription></CardHeader><CardContent className="flex gap-2"><Input value={sessionName} onChange={e => setSessionName(e.target.value)} placeholder="2026/2027"/><Button onClick={() => createSession.mutate()} disabled={createSession.isPending}><Save className="size-4"/>Create</Button></CardContent></Card>}<div className="grid gap-4 md:grid-cols-3">{(sessions.data ?? []).map(s => <Card key={s.id}><CardContent className="p-5"><CalendarDays className="mb-3 size-5 text-primary"/><p className="font-semibold">{s.name}</p><p className="text-sm text-muted-foreground">{s.is_current ? "Current session" : "Academic session"}</p></CardContent></Card>)}</div>{!sessions.isLoading && !sessions.data?.length && <EmptyState icon={FileText} title="No academic sessions" description="Create your first academic session above."/>}<Card><CardHeader><CardTitle>Terms</CardTitle><CardDescription>{terms.data?.length ?? 0} configured terms</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{(terms.data ?? []).map(t => <div key={t.id} className="rounded-xl border p-4"><p className="font-medium">{t.name}</p><p className="text-xs text-muted-foreground">{t.is_current ? "Current term" : "Configured"}</p></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="assessments" className="space-y-5">{isManager && <Card><CardHeader><CardTitle>Create assessment</CardTitle><CardDescription>Tests, exams, quizzes and continuous assessment.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="lg:col-span-3"><Label>Title</Label><Input value={assessment.title} onChange={e=>setAssessment({...assessment,title:e.target.value})} placeholder="First Continuous Assessment"/></div><Select value={assessment.class_id} onValueChange={v=>setAssessment({...assessment,class_id:v})}><SelectTrigger><SelectValue placeholder="Class"/></SelectTrigger><SelectContent>{(classes.data??[]).filter(c=>!c.is_archived).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select><Select value={assessment.subject_id} onValueChange={v=>setAssessment({...assessment,subject_id:v})}><SelectTrigger><SelectValue placeholder="Subject"/></SelectTrigger><SelectContent>{(subjects.data??[]).filter(s=>!s.is_archived).map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={assessment.term_id} onValueChange={v=>setAssessment({...assessment,term_id:v})}><SelectTrigger><SelectValue placeholder="Term"/></SelectTrigger><SelectContent>{(terms.data??[]).map(t=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select><Input value={assessment.type} onChange={e=>setAssessment({...assessment,type:e.target.value})} placeholder="Test / Exam"/><Input type="number" min="1" value={assessment.max_score} onChange={e=>setAssessment({...assessment,max_score:e.target.value})} placeholder="Maximum score"/><Button onClick={()=>createAssessment.mutate()} disabled={createAssessment.isPending}><Plus className="size-4"/>Create assessment</Button></CardContent></Card>}{(assessments.data??[]).map(a=><Card key={a.id}><CardContent className="flex items-center justify-between gap-4 p-4"><div><p className="font-medium">{a.title}</p><p className="text-sm text-muted-foreground">{a.assessment_type} · {a.max_score} marks · {a.published ? "Published" : "Draft"}</p></div>{isManager&&<Button variant="ghost" size="icon" onClick={()=>remove.mutate({table:"assessments",id:a.id})}><Trash2 className="size-4"/></Button>}</CardContent></Card>)}</TabsContent>
      <TabsContent value="learning" className="space-y-5">{isManager && <Card><CardHeader><CardTitle>Publish assignment</CardTitle><CardDescription>Give students structured work with deadlines.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Title</Label><Input value={assignment.title} onChange={e=>setAssignment({...assignment,title:e.target.value})} placeholder="Solve quadratic equations"/></div><Select value={assignment.class_id} onValueChange={v=>setAssignment({...assignment,class_id:v})}><SelectTrigger><SelectValue placeholder="Class"/></SelectTrigger><SelectContent>{(classes.data??[]).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select><Select value={assignment.subject_id} onValueChange={v=>setAssignment({...assignment,subject_id:v})}><SelectTrigger><SelectValue placeholder="Subject"/></SelectTrigger><SelectContent>{(subjects.data??[]).map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Textarea className="sm:col-span-2" value={assignment.description} onChange={e=>setAssignment({...assignment,description:e.target.value})} placeholder="Instructions and description"/><Input type="datetime-local" value={assignment.due_at} onChange={e=>setAssignment({...assignment,due_at:e.target.value})}/><Button onClick={()=>createAssignment.mutate()} disabled={createAssignment.isPending}><Plus className="size-4"/>Publish assignment</Button></CardContent></Card>}{(assignments.data??[]).map(a=><Card key={a.id}><CardContent className="flex items-center justify-between p-4"><div><p className="font-medium">{a.title}</p><p className="text-sm text-muted-foreground">{a.status} · {a.due_at ? new Date(a.due_at).toLocaleString() : "No deadline"}</p></div>{isManager&&<Button variant="ghost" size="icon" onClick={()=>remove.mutate({table:"assignments",id:a.id})}><Trash2 className="size-4"/></Button>}</CardContent></Card>)}{!assignments.data?.length&&<EmptyState icon={ClipboardCheck} title="No assignments" description="Published learning work will appear here."/>}</TabsContent>
      <TabsContent value="communication" className="space-y-5">{isManager && <Card><CardHeader><CardTitle>New announcement</CardTitle><CardDescription>Publish a message to your school community.</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})} placeholder="Announcement title"/><Select value={announcement.audience} onValueChange={v=>setAnnouncement({...announcement,audience:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Everyone</SelectItem><SelectItem value="students">Students</SelectItem><SelectItem value="teachers">Teachers</SelectItem><SelectItem value="parents">Parents</SelectItem><SelectItem value="staff">Staff</SelectItem></SelectContent></Select><Textarea value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})} rows={5} placeholder="Write your message..."/><Button onClick={()=>createAnnouncement.mutate()} disabled={createAnnouncement.isPending}><Megaphone className="size-4"/>Publish announcement</Button></CardContent></Card>}{(announcements.data??[]).map(a=><Card key={a.id}><CardContent className="flex gap-4 p-5"><Megaphone className="mt-1 size-5 text-primary"/><div className="min-w-0 flex-1"><p className="font-semibold">{a.title}</p><p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{a.body}</p><p className="mt-3 text-xs text-muted-foreground">Audience: {a.audience} · {new Date(a.created_at).toLocaleString()}</p></div>{isManager&&<Button variant="ghost" size="icon" onClick={()=>remove.mutate({table:"announcements",id:a.id})}><Trash2 className="size-4"/></Button>}</CardContent></Card>)}</TabsContent>
    </Tabs>
  </AppShell>;
}
