import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FileText, Loader2, RefreshCw } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { AppShell, EmptyState, useSchoolId } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { api } from "@/lib/queries";
import { useAuth } from "@/lib/auth";
export const Route = createFileRoute("/_authenticated/report-cards")({ component: ReportCards });
type ReportCardItem={id:string;student_id:string;session_id:string;term_id:string;average_score:number|null;position:number|null;status:string;students:{first_name:string;last_name:string;student_id:string}|null;academic_sessions:{name:string}|null;terms:{name:string}|null};
function ReportCards(){const schoolId=useSchoolId();const{isManager}=useAuth();const qc=useQueryClient();const[sessionId,setSessionId]=useState("");const[termId,setTermId]=useState("");const q=useQuery<ReportCardItem[]>({queryKey:["report-cards",schoolId],enabled:!!schoolId,queryFn:async()=>{const{data,error}=await supabase.from("report_cards").select("id,student_id,session_id,term_id,average_score,position,status,students(first_name,last_name,student_id),academic_sessions(name),terms(name)").eq("school_id",schoolId!).order("updated_at",{ascending:false}).limit(100);if(error)throw error;return(data??[]) as ReportCardItem[]}});const sessions=useQuery({queryKey:["sessions",schoolId],enabled:!!schoolId,queryFn:()=>api.sessions(schoolId!)});const terms=useQuery({queryKey:["terms",schoolId],enabled:!!schoolId,queryFn:()=>api.terms(schoolId!)});const selectedSession=sessionId||sessions.data?.find(s=>s.is_current)?.id||sessions.data?.[0]?.id||"";const selectedTerm=termId||terms.data?.find(t=>t.is_current&&t.session_id===selectedSession)?.id||terms.data?.find(t=>t.session_id===selectedSession)?.id||"";
const generate=useMutation({mutationFn:async()=>{if(!schoolId||!selectedSession||!selectedTerm)throw new Error("Select an academic session and term");const{data:students,error:studentError}=await supabase.from("students").select("id,class_id").eq("school_id",schoolId).eq("is_archived",false);if(studentError)throw studentError;const{data:assessments,error:assessmentError}=await supabase.from("assessments").select("id,max_score").eq("school_id",schoolId).eq("session_id",selectedSession).eq("term_id",selectedTerm);if(assessmentError)throw assessmentError;const ids=(assessments??[]).map(a=>a.id);const{data:scores,error:scoreError}=ids.length?await supabase.from("assessment_scores").select("student_id,assessment_id,score").eq("school_id",schoolId).in("assessment_id",ids):{data:[],error:null};if(scoreError)throw scoreError;const maxMap=new Map((assessments??[]).map(a=>[a.id,Number(a.max_score)]));const rows=(students??[]).map(s=>{const own=(scores??[]).filter(x=>x.student_id===s.id);const total=own.reduce((n,x)=>n+Number(x.score??0),0);const max=own.reduce((n,x)=>n+(maxMap.get(x.assessment_id)??0),0);return{student_id:s.id,class_id:s.class_id,total_score:total,average_score:max?total/max*100:0};}).sort((a,b)=>b.average_score-a.average_score);const payload=rows.map((r,i)=>({school_id:schoolId,student_id:r.student_id,session_id:selectedSession,term_id:selectedTerm,class_id:r.class_id,total_score:r.total_score,average_score:Number(r.average_score.toFixed(2)),position:i+1,status:"published",published_at:new Date().toISOString()}));if(payload.length){const{error}=await supabase.from("report_cards").upsert(payload,{onConflict:"student_id,session_id,term_id"});if(error)throw error;}return payload.length;},onSuccess:async count=>{toast.success(`${count} report cards generated and published`);await qc.invalidateQueries({queryKey:["report-cards",schoolId]});},onError:e=>toast.error(e.message)});
return <AppShell title="Report Cards" description="Generate, review and publish academic report cards">{isManager&&<Card className="mb-6"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><RefreshCw className="size-4"/> Generate report cards</CardTitle><CardDescription>Build term averages from recorded assessment scores and publish them to student and parent portals.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><Select value={selectedSession} onValueChange={setSessionId}><SelectTrigger><SelectValue placeholder="Session"/></SelectTrigger><SelectContent>{(sessions.data??[]).map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={selectedTerm} onValueChange={setTermId}><SelectTrigger><SelectValue placeholder="Term"/></SelectTrigger><SelectContent>{(terms.data??[]).filter(t=>t.session_id===selectedSession).map(t=><SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>)}</SelectContent></Select><Button onClick={()=>generate.mutate()} disabled={generate.isPending||!selectedSession||!selectedTerm}>{generate.isPending?<Loader2 className="size-4 animate-spin"/>:<RefreshCw className="size-4"/>} Generate & publish</Button></CardContent></Card>}{!isManager&&<div className="mb-4 rounded-xl border bg-muted/40 p-4 text-sm text-muted-foreground">Published report cards for your linked account are available through your portal.</div>}{q.isLoading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="size-6 animate-spin"/></div>:q.isError?<p className="text-sm text-destructive">Could not load report cards.</p>:q.data?.length===0?<EmptyState icon={FileText} title="No report cards yet" description="Generate report cards after assessment scores are available."/>:<Card><CardHeader><CardTitle className="text-base">Recent report cards</CardTitle></CardHeader><CardContent className="space-y-2">{q.data?.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-medium">{r.students?.first_name} {r.students?.last_name}</p><p className="text-xs text-muted-foreground">{r.students?.student_id} · {r.academic_sessions?.name} · {r.terms?.name}</p></div><div className="flex items-center gap-3"><div className="text-right"><p className="font-semibold">{r.average_score??0}%</p><p className="text-xs text-muted-foreground">Average</p></div>{typeof r.position==="number"&&<Badge variant="secondary">#{r.position}</Badge>}<Badge variant={r.status==="published"?"default":"outline"}>{r.status}</Badge></div></div>)}</CardContent></Card>}</AppShell>;
}
