import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CreditCard, Loader2, Plus, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell, useSchool, useSchoolId } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { api, logActivity } from "@/lib/queries";
import { useAuth } from "@/lib/auth";

export const Route = createFileRoute("/_authenticated/settings")({ component: SettingsPage });

type SchoolSettings = { school_id: string; timezone: string; currency: string; locale: string; date_format: string; week_starts_on: number; default_page_size: number };
type Subscription = { status: string; billing_cycle: string; trial_ends_at: string | null; current_period_end: string | null; saas_plans: { name: string; max_students: number | null; max_teachers: number | null; ai_tokens_monthly: number | null } | null };

function SettingsPage() {
  const schoolId = useSchoolId();
  const { user, profile, isManager } = useAuth();
  const queryClient = useQueryClient();
  const schoolQuery = useSchool();
  const [form, setForm] = useState({ name: "", email: "", phone: "", address: "", website: "", logo_url: "" });
  const [newSession, setNewSession] = useState("");
  const [newTerm, setNewTerm] = useState("");
  const [config, setConfig] = useState<SchoolSettings | null>(null);

  useEffect(() => { const s = schoolQuery.data; if (s) setForm({ name:s.name,email:s.email??"",phone:s.phone??"",address:s.address??"",website:s.website??"",logo_url:s.logo_url??"" }); }, [schoolQuery.data]);
  const sessionsQuery = useQuery({ queryKey:["sessions",schoolId], enabled:!!schoolId, queryFn:()=>api.sessions(schoolId!) });
  const termsQuery = useQuery({ queryKey:["terms",schoolId], enabled:!!schoolId, queryFn:()=>api.terms(schoolId!) });
  const configQuery = useQuery({ queryKey:["school-settings-config",schoolId], enabled:!!schoolId && isManager, queryFn:async()=>{ const {data,error}=await (supabase as any).from("school_settings").select("school_id,timezone,currency,locale,date_format,week_starts_on,default_page_size").eq("school_id",schoolId!).single(); if(error)throw error; return data as SchoolSettings; }, });
  const subscriptionQuery = useQuery({ queryKey:["school-subscription",schoolId], enabled:!!schoolId, queryFn:async()=>{ const {data,error}=await (supabase as any).from("school_subscriptions").select("status,billing_cycle,trial_ends_at,current_period_end,saas_plans(name,max_students,max_teachers,ai_tokens_monthly)").eq("school_id",schoolId!).maybeSingle(); if(error)throw error; return data as Subscription | null; }, });
  useEffect(()=>{if(configQuery.data)setConfig(configQuery.data)},[configQuery.data]);
  const currentSession=(sessionsQuery.data??[]).find(s=>s.is_current)??null;
  const saveSchool=useMutation({ mutationFn:async()=>{if(!schoolId)throw new Error("No school");if(!form.name.trim())throw new Error("School name is required");const {error}=await supabase.from("schools").update({name:form.name.trim(),email:form.email.trim()||null,phone:form.phone.trim()||null,address:form.address.trim()||null,website:form.website.trim()||null,logo_url:form.logo_url.trim()||null}).eq("id",schoolId);if(error)throw new Error(error.message);if(user)await logActivity({schoolId,actorId:user.id,actorName:profile?.full_name||user.email||"Admin",action:"updated",entity:"school",description:"Updated school information"})},onSuccess:async()=>{toast.success("School information saved");await queryClient.invalidateQueries({queryKey:["school",schoolId]})},onError:(e:Error)=>toast.error(e.message)});
  const saveConfig=useMutation({ mutationFn:async()=>{if(!config||!schoolId)throw new Error("No school configuration");const {error}=await (supabase as any).from("school_settings").update({timezone:config.timezone.trim(),currency:config.currency.trim().toUpperCase(),locale:config.locale.trim(),date_format:config.date_format.trim(),week_starts_on:Math.min(6,Math.max(0,Number(config.week_starts_on)||0)),default_page_size:Math.min(100,Math.max(10,Number(config.default_page_size)||25))}).eq("school_id",schoolId);if(error)throw new Error(error.message)},onSuccess:async()=>{toast.success("School configuration saved");await queryClient.invalidateQueries({queryKey:["school-settings-config",schoolId]})},onError:(e:Error)=>toast.error(e.message)});
  const addSession=useMutation({mutationFn:async()=>{if(!schoolId)throw new Error("No school");const name=newSession.trim();if(!name)throw new Error("Enter a session name");const {error}=await supabase.from("academic_sessions").insert({school_id:schoolId,name,is_current:(sessionsQuery.data??[]).length===0});if(error)throw new Error(error.message)},onSuccess:async()=>{toast.success("Session added");setNewSession("");await queryClient.invalidateQueries({queryKey:["sessions",schoolId]})},onError:(e:Error)=>toast.error(e.message)});
  const setCurrentSession=useMutation({mutationFn:async(sessionId:string)=>{if(!schoolId)throw new Error("No school");const {error:e1}=await supabase.from("academic_sessions").update({is_current:false}).eq("school_id",schoolId);if(e1)throw new Error(e1.message);const {error:e2}=await supabase.from("academic_sessions").update({is_current:true}).eq("id",sessionId);if(e2)throw new Error(e2.message)},onSuccess:async()=>{toast.success("Current session updated");await queryClient.invalidateQueries({queryKey:["sessions",schoolId]});await queryClient.invalidateQueries({queryKey:["dashboard",schoolId]})},onError:(e:Error)=>toast.error(e.message)});
  const addTerm=useMutation({mutationFn:async()=>{if(!schoolId||!currentSession)throw new Error("Create a current session first");const name=newTerm.trim();if(!name)throw new Error("Enter a term name");const {error}=await supabase.from("terms").insert({school_id:schoolId,session_id:currentSession.id,name,is_current:(termsQuery.data??[]).filter(t=>t.session_id===currentSession.id).length===0});if(error)throw new Error(error.message)},onSuccess:async()=>{toast.success("Term added");setNewTerm("");await queryClient.invalidateQueries({queryKey:["terms",schoolId]})},onError:(e:Error)=>toast.error(e.message)});
  const setCurrentTerm=useMutation({mutationFn:async(termId:string)=>{if(!schoolId)throw new Error("No school");const {error:e1}=await supabase.from("terms").update({is_current:false}).eq("school_id",schoolId);if(e1)throw new Error(e1.message);const {error:e2}=await supabase.from("terms").update({is_current:true}).eq("id",termId);if(e2)throw new Error(e2.message)},onSuccess:async()=>{toast.success("Current term updated");await queryClient.invalidateQueries({queryKey:["terms",schoolId]});await queryClient.invalidateQueries({queryKey:["dashboard",schoolId]})},onError:(e:Error)=>toast.error(e.message)});
  const sessionTerms=(termsQuery.data??[]).filter(t=>!currentSession||t.session_id===currentSession.id);
  return <AppShell title="Settings" description="School profile, configuration, subscription and academic setup">
    {!isManager?<Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Only school managers can change settings.</CardContent></Card>:schoolQuery.isLoading?<div className="flex justify-center py-24"><Loader2 className="size-6 animate-spin text-muted-foreground"/></div>:schoolQuery.isError?<p className="text-sm text-destructive">Could not load school settings.</p>:<div className="grid gap-6 lg:grid-cols-2">
      <Card><CardHeader><CardTitle className="text-base">School information</CardTitle><CardDescription>These details appear across your workspace.</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label>School name *</Label><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Email</Label><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Phone</Label><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div></div><div><Label>Address</Label><Input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Website</Label><Input value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div><div><Label>Logo URL</Label><Input value={form.logo_url} onChange={e=>setForm({...form,logo_url:e.target.value})}/></div></div><Button onClick={()=>saveSchool.mutate()} disabled={saveSchool.isPending}>Save school</Button></CardContent></Card>
      <div className="space-y-6"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="size-4"/>Workspace configuration</CardTitle><CardDescription>Locale and formatting defaults for this school.</CardDescription></CardHeader><CardContent className="space-y-4">{config?<><div className="grid gap-4 sm:grid-cols-2"><div><Label>Timezone</Label><Input value={config.timezone} onChange={e=>setConfig({...config,timezone:e.target.value})}/></div><div><Label>Currency</Label><Input value={config.currency} onChange={e=>setConfig({...config,currency:e.target.value})}/></div><div><Label>Locale</Label><Input value={config.locale} onChange={e=>setConfig({...config,locale:e.target.value})}/></div><div><Label>Date format</Label><Input value={config.date_format} onChange={e=>setConfig({...config,date_format:e.target.value})}/></div><div><Label>Week starts on (0–6)</Label><Input type="number" min="0" max="6" value={config.week_starts_on} onChange={e=>setConfig({...config,week_starts_on:Number(e.target.value)})}/></div><div><Label>Default page size</Label><Input type="number" min="10" max="100" value={config.default_page_size} onChange={e=>setConfig({...config,default_page_size:Number(e.target.value)})}/></div></div><Button variant="secondary" onClick={()=>saveConfig.mutate()} disabled={saveConfig.isPending}>Save configuration</Button></>:<Loader2 className="size-5 animate-spin"/>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CreditCard className="size-4"/>Subscription</CardTitle><CardDescription>Your current platform plan and limits.</CardDescription></CardHeader><CardContent>{subscriptionQuery.isLoading?<Loader2 className="size-5 animate-spin"/>:subscriptionQuery.data?<div className="space-y-3"><div className="flex items-center justify-between"><span className="font-semibold">{subscriptionQuery.data.saas_plans?.name??"Plan"}</span><Badge variant={subscriptionQuery.data.status==="active"?"default":"secondary"}>{subscriptionQuery.data.status}</Badge></div><div className="grid grid-cols-3 gap-2 text-xs text-muted-foreground"><span>Students: {subscriptionQuery.data.saas_plans?.max_students??"∞"}</span><span>Teachers: {subscriptionQuery.data.saas_plans?.max_teachers??"∞"}</span><span>AI: {subscriptionQuery.data.saas_plans?.ai_tokens_monthly?.toLocaleString()??"∞"}</span></div><p className="text-xs text-muted-foreground">Billing cycle: {subscriptionQuery.data.billing_cycle}. {subscriptionQuery.data.current_period_end?`Current period ends ${new Date(subscriptionQuery.data.current_period_end).toLocaleDateString()}.`:""}</p></div>:<p className="text-sm text-muted-foreground">No subscription record.</p>}</CardContent></Card></div>
      <div className="space-y-6"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="size-4"/>Academic sessions</CardTitle><CardDescription>The current session drives dashboards and reports.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={newSession} placeholder="e.g. 2026/2027" onChange={e=>setNewSession(e.target.value)}/><Button variant="secondary" onClick={()=>addSession.mutate()} disabled={addSession.isPending}><Plus className="size-4"/>Add</Button></div><ul className="space-y-2">{(sessionsQuery.data??[]).map(s=><li key={s.id} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span className="font-medium">{s.name}</span>{s.is_current?<Badge>Current</Badge>:<Button variant="ghost" size="sm" onClick={()=>setCurrentSession.mutate(s.id)}>Make current</Button>}</li>)}</ul></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Terms</CardTitle><CardDescription>{currentSession?`Terms in ${currentSession.name}`:"Create a current session first."}</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={newTerm} placeholder="e.g. First Term" disabled={!currentSession} onChange={e=>setNewTerm(e.target.value)}/><Button variant="secondary" onClick={()=>addTerm.mutate()} disabled={addTerm.isPending||!currentSession}><Plus className="size-4"/>Add</Button></div><ul className="space-y-2">{sessionTerms.map(t=><li key={t.id} className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm"><span className="font-medium">{t.name}</span>{t.is_current?<Badge>Current</Badge>:<Button variant="ghost" size="sm" onClick={()=>setCurrentTerm.mutate(t.id)}>Make current</Button>}</li>)}</ul></CardContent></Card></div>
    </div>}
  </AppShell>;
}
