import { createFileRoute } from "@tanstack/react-router";
import { useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Clock3, Download, LogIn, LogOut, UserCheck } from "lucide-react";
import { toast } from "sonner";
import { AppShell, EmptyState, useSchoolId } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { api } from "@/lib/queries";
import { useAuth } from "@/lib/auth";

type Row={id:string;teacher_id:string;attendance_date:string;clock_in:string|null;clock_out:string|null;note:string|null};
export const Route=createFileRoute("/_authenticated/teacher-attendance")({component:TeacherAttendancePage});
function csv(rows:string[][]){const text=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv"}));a.download="teacher-attendance.csv";a.click();}
function TeacherAttendancePage(){
 const schoolId=useSchoolId();const {user,primaryRole,isManager}=useAuth();const qc=useQueryClient();const canView=isManager||primaryRole==="secretary"||primaryRole==="teacher";
 const teachers=useQuery({queryKey:["teachers",schoolId],enabled:!!schoolId&&canView,queryFn:()=>api.teachers(schoolId!)});
 const records=useQuery({queryKey:["teacher-attendance",schoolId],enabled:!!schoolId&&canView,queryFn:async()=>{const {data,error}=await supabase.from("teacher_attendance").select("id,teacher_id,attendance_date,clock_in,clock_out,note").order("attendance_date",{ascending:false}).limit(200);if(error)throw new Error(error.message);return (data??[]) as Row[];}});
 const me=useMemo(()=> (teachers.data??[]).find(t=>t.user_id===user?.id),[teachers.data,user?.id]);
 const today=useMemo(()=> (records.data??[]).find(r=>r.teacher_id===me?.id&&r.attendance_date===new Date().toISOString().slice(0,10)),[records.data,me]);
 const clockIn=useMutation({mutationFn:async()=>{if(!me)throw new Error("Your account is not linked to a teacher record");const {error}=await supabase.rpc("clock_in_teacher",{p_teacher_id:me.id});if(error)throw new Error(error.message);},onSuccess:async()=>{toast.success("Clocked in");await qc.invalidateQueries({queryKey:["teacher-attendance",schoolId]});},onError:e=>toast.error(e.message)});
 const clockOut=useMutation({mutationFn:async()=>{if(!me)throw new Error("Your account is not linked to a teacher record");const {error}=await supabase.rpc("clock_out_teacher",{p_teacher_id:me.id});if(error)throw new Error(error.message);},onSuccess:async()=>{toast.success("Clocked out");await qc.invalidateQueries({queryKey:["teacher-attendance",schoolId]});},onError:e=>toast.error(e.message)});
 if(!canView)return <AppShell title="Teacher Attendance"><EmptyState icon={UserCheck} title="Access restricted" description="Teacher attendance is available to teachers, the Secretary and school managers."/></AppShell>;
 return <AppShell title="Teacher Attendance" description="Clock in, clock out and review staff attendance"><div className="space-y-5">{primaryRole==="teacher"&&<Card><CardHeader><CardTitle>Today's attendance</CardTitle></CardHeader><CardContent className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{me?`${me.first_name} ${me.last_name}`:"Teacher record not linked"}</p><p className="text-sm text-muted-foreground">{today?.clock_in?`Clocked in ${new Date(today.clock_in).toLocaleTimeString()}`:"Not clocked in yet"}{today?.clock_out?` · Clocked out ${new Date(today.clock_out).toLocaleTimeString()}`:""}</p></div><div className="flex gap-2">{!today?.clock_in?<Button onClick={()=>clockIn.mutate()} disabled={clockIn.isPending||!me}><LogIn className="size-4"/>Clock in</Button>:<Button variant="outline" onClick={()=>clockOut.mutate()} disabled={clockOut.isPending||!!today.clock_out}><LogOut className="size-4"/>Clock out</Button>}</div></CardContent></Card>}
 {isManager||primaryRole==="secretary"?<Card><CardHeader className="flex flex-row items-center justify-between gap-3"><CardTitle>Attendance history</CardTitle><Button variant="outline" size="sm" onClick={()=>csv([["Date","Teacher","Staff ID","Clock in","Clock out"],...(records.data??[]).map(r=>{const t=(teachers.data??[]).find(x=>x.id===r.teacher_id);return [r.attendance_date,t?`${t.first_name} ${t.last_name}`:"Unknown",t?.staff_id??"",r.clock_in?new Date(r.clock_in).toISOString():"",r.clock_out?new Date(r.clock_out).toISOString():""];})])}><Download className="size-4"/>Export CSV</Button></CardHeader><CardContent><div className="space-y-2">{(records.data??[]).length===0?<p className="py-10 text-center text-sm text-muted-foreground">No teacher attendance records yet.</p>:(records.data??[]).slice(0,60).map(r=>{const t=(teachers.data??[]).find(x=>x.id===r.teacher_id);return <div key={r.id} className="flex flex-col gap-2 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{t?`${t.first_name} ${t.last_name}`:"Unknown teacher"}</p><p className="text-xs text-muted-foreground">{r.attendance_date} · {t?.staff_id}</p></div><div className="flex items-center gap-2 text-sm">{r.clock_in?<Badge variant="secondary">In {new Date(r.clock_in).toLocaleTimeString()}</Badge>:<Badge variant="outline">No clock-in</Badge>}{r.clock_out?<Badge>Out {new Date(r.clock_out).toLocaleTimeString()}</Badge>:r.clock_in?<Badge variant="destructive">Active</Badge>:null}</div></div>})}</div></CardContent></Card>:<Card><CardContent className="flex items-center gap-3 p-5 text-sm text-muted-foreground"><Clock3 className="size-5"/>Your recent clock-in records appear here after you start using the time tracker.</CardContent></Card>}</div></AppShell>;
}